
version: "3.9"

volumes:
  pg14_postgres_data_local: {}
  pg14_postgres_backup_local: {}
  # v14_meilisearch_data_local: {}

services:
  db_postgres:
    platform: linux/amd64
    build: ./docker/production/postgres/
    image: test_demo1_production_postgres
    volumes:
      - pg14_postgres_data_local:/var/lib/postgresql/data
      - pg14_postgres_backup_local:/backups
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.personal/.postgres
    ports:
      - "5432:5432"
  web_django:
    platform: linux/amd64
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start-web_django
    image: test_demo1_local_web_django
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.personal/.postgres
    depends_on:
      - db_postgres
  # meilisearch:
  #   platform: linux/amd64
  #   build: ./docker/production/meilisearch/
  #   restart: unless-stopped
  #   ports:
  #     - "7700:7700"
  #   volumes:
  #     - v14_meilisearch_data_local:/data.ms
  #   env_file:
  #     - ./.envs/.local/.meilisearch
  #     - ./.envs/.personal/.meilisearch
  # meilisync:
  #   platform: linux/amd64
  #   image: long2ice/meilisync
  #   volumes:
  #     - ./config.yml:/meilisync/config.yml

